# Generated by Django 6.0.1 on 2026-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_Email', models.CharField(max_length=20, unique=True)),
                ('Organization_UserName', models.CharField(max_length=30, unique=True)),
                ('Organization_Name', models.CharField(max_length=20)),
                ('Organization_Contact', models.BigIntegerField()),
                ('Organization_Profile', models.CharField(blank=True, max_length=20, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
