# Generated by Django 6.0.1 on 2026-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='Organization_Profile',
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_profiles/'),
        ),
    ]
