# Generated by Django 6.0.1 on 2026-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_organization_organization_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Organization_Email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
