# Generated by Django 6.0.1 on 2026-02-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_organization_organization_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scorecards/')),
                ('summary_text', models.TextField()),
                ('ai_provider', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.organization')),
            ],
        ),
    ]
