# Generated by Django 6.0.1 on 2026-02-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_scorecardanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('Tournament_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10)),
                ('PrizePool', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Organization_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='web.organization')),
            ],
        ),
    ]
