# Generated by Django 6.0.1 on 2026-02-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_organization_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='web.organization'),
        ),
    ]
