# Generated by Django 6.0.1 on 2026-02-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_otp'),
        ('web', '0006_player_organization'),
    ]

    operations = [
    ]
