# Generated by Django 6.0.1 on 2026-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_organization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
