# Generated by Django 6.0.1 on 2026-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_player_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_profiles/'),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
