# Generated by Django 6.0.1 on 2026-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_distribution',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tournament',
            name='roadmap_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_roadmap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
