# Generated by Django 6.0.1 on 2026-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_playertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
