# Generated by Django 6.0.1 on 2026-02-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_tournament_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bidding_open',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrganizationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='INFO', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='web.organization')),
                ('related_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='web.organization')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='web.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'organization')},
            },
        ),
    ]
