# Generated by Django 6.0.1 on 2026-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_tournament_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
