# Generated by Django 6.0.1 on 2026-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_tournament_bidding_open_organizationnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
