# Generated by Django 6.0.1 on 2026-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_organization_coins_player_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bidding_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bidding_invite_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bidding_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
