# Generated by Django 6.0.1 on 2026-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_playerbid_playernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_start_time', models.DateTimeField(blank=True, null=True)),
                ('bidding_end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
