# Generated by Django 6.0.1 on 2026-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bidding_notifications_sent',
            field=models.BooleanField(default=False),
        ),
    ]
