# Generated by Django 6.0.1 on 2026-02-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_organization_is_archived_player_is_archived'),
        ('web', '0021_tournament_bidding_notifications_sent'),
    ]

    operations = [
    ]
