# Generated by Django 6.0.1 on 2026-02-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_merge_20260215_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
