# Generated by Django 6.0.1 on 2026-03-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentbidder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tournamentbidder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tournamentbidder',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bidding_end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bidding_invite_fee',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bidding_notifications_sent',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bidding_open',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bidding_start_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.DeleteModel(
            name='PlayerBid',
        ),
        migrations.DeleteModel(
            name='TournamentBidder',
        ),
    ]
