# Generated by Django 6.0.1 on 2026-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_delete_globalsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
