# Generated by Django 6.0.1 on 2026-03-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_biddingseason_alter_transaction_transaction_type_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently performing scheduled maintenance. Please check back soon!')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
