# Generated by Django 6.0.1 on 2026-03-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingseason',
            name='auto_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biddingseason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BiddingSeasonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='web.biddingseason')),
            ],
        ),
    ]
