# Generated by Django 6.0.1 on 2026-03-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_biddingseason_auto_start_biddingseason_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_org_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_player_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='announcement_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='admin@egamescout.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_org_coins',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_player_coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_name',
            field=models.CharField(default='EGAMESCOUT', max_length=100),
        ),
    ]
