# Generated by Django 6.0.1 on 2026-03-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('web', '0028_systemsettings_allow_org_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('ORG', 'Organization'), ('PLAYER', 'Player')], max_length=20)),
                ('user_id', models.IntegerField()),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_remember_me', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'db_table': 'secure_user_sessions',
                'indexes': [models.Index(fields=['user_type', 'user_id', 'is_active'], name='secure_user_user_ty_729097_idx')],
            },
        ),
    ]
