# Generated by Django 6.0.1 on 2026-03-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_seen_player_setup_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_player_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('game_id', models.CharField(max_length=50)),
                ('status_label', models.CharField(default='Added Manually', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_players', to='web.organization')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_affiliations', to='web.player')),
            ],
            options={
                'unique_together': {('organization', 'player')},
            },
        ),
    ]
