# Generated by Django 6.0.1 on 2026-03-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_organization_has_seen_player_setup_popup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_tournaments', to='web.organization')),
                ('players', models.ManyToManyField(blank=True, related_name='tournament_participations', to='web.organizationplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='web.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'organization')},
            },
        ),
    ]
