# Generated by Django 6.0.1 on 2026-03-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_tournamentbidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentbidder',
            name='players',
        ),
    ]
