# Generated by Django 6.0.1 on 2026-03-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_remove_m2m_from_tournamentbidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_affiliations', to='web.player'),
        ),
    ]
