# Generated by Django 6.0.1 on 2026-03-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_verification_badges_and_tournament_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('winner_team', models.CharField(blank=True, max_length=255, null=True)),
                ('runner_up_team', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('match_data', models.JSONField(help_text='Raw JSON data of the match scoreboard')),
                ('ai_analysis', models.TextField(help_text='AI generated summary for this match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='web.previoustournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_teams', to='web.previoustournament')),
            ],
        ),
    ]
