# Generated by Django 6.0.1 on 2026-03-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_previoustournament_tournamentscorecard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previoustournament',
            name='created_at',
        ),
        migrations.AddField(
            model_name='previoustournament',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_tournaments', to='web.organization'),
        ),
        migrations.AlterField(
            model_name='previoustournament',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
