# Generated by Django 6.0.1 on 2026-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_remove_previoustournament_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active_account',
            field=models.BooleanField(default=True),
        ),
    ]
