# Generated by Django 6.0.1 on 2026-03-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_organization_is_active_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='web.player'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other'), ('BID_LOCKED', 'Bid Locked'), ('BID_ACCEPTED', 'Bid Accepted'), ('BID_REFUND', 'Bid Refund'), ('ADMIN_GRANT', 'Admin Grant'), ('BID_PAYMENT', 'Bid Payment')], default='OTHER', max_length=50),
        ),
    ]
