# Generated by Django 6.0.1 on 2026-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_organization_archived_at_player_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationplayer',
            name='position',
            field=models.CharField(default='Player', max_length=50),
        ),
    ]
