# Generated by Django 6.0.1 on 2026-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_roleconflictrequest_alter_organization_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleconflictrequest',
            name='request_data',
            field=models.JSONField(blank=True, help_text='Stores registration payload pending approval', null=True),
        ),
    ]
