# Generated by Django 6.0.1 on 2026-03-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_roleconflictrequest_request_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleConflictRequest',
        ),
    ]
