# Generated by Django 6.0.1 on 2026-03-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_roleconflictrequest_request_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_signature',
            field=models.ImageField(blank=True, null=True, upload_to='organization_signatures/'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('responsibilities', models.TextField()),
                ('sponsor_promotion', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('termination_rules', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='web.organization')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='web.player')),
            ],
        ),
    ]
