# Generated by Django 6.0.1 on 2026-03-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_organization_organization_signature_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardanalysis',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='web.previoustournament'),
        ),
    ]
