# Generated by Django 6.0.1 on 2026-03-19 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_delete_roleconflictrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoustournament',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
