# Generated by Django 6.0.1 on 2026-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_scorecardanalysis_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardanalysis',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Stored JSON data from AI', null=True),
        ),
    ]
