# Generated by Django 6.0.1 on 2026-03-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_alter_previoustournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='previoustournament',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='previous_tournaments/covers/'),
        ),
        migrations.AddField(
            model_name='previoustournament',
            name='game_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
