# Generated by Django 6.0.1 on 2026-03-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_previoustournament_cover_image_and_more'),
        ('web', '0047_scorecardanalysis_raw_data'),
    ]

    operations = [
    ]
