# Generated by Django 6.0.1 on 2026-03-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_player_is_2fa_enabled_player_totp_secret'),
        ('web', '0048_merge_20260319_2236'),
    ]

    operations = [
    ]
