# Generated by Django 6.0.1 on 2026-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_merge_20260320_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('PLAYER', 'Player'), ('ORGANIZATION', 'Organization'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
