# Generated by Django 6.0.1 on 2026-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_systemlog_organization_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
