# Generated by Django 6.0.1 on 2026-04-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_playertask_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
