# Generated by Django 6.0.1 on 2026-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_bid_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_role',
            field=models.CharField(blank=True, choices=[('IGL(In Game Leader)', 'IGL(In Game Leader)'), ('Fragger', 'Fragger'), ('Assaulter', 'Assaulter'), ('Freeman', 'Freeman'), ('Support', 'Support')], help_text='Select your primary in-game role', max_length=50, null=True),
        ),
    ]
