# Generated by Django 6.0.1 on 2026-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_player_skill_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='discord_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='youtube_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
