# Generated by Django 6.0.1 on 2026-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_player_discord_link_player_discord_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='player_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/signatures/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
